site_name: TEURA
site_url: https://teura.eu/
site_description: Your R&D partner from concept to deployment.
site_author: Patryk Balazy
theme:
  name: mkdocs
nav:
  - Home: index.md
plugins:
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: pl
          name: Polski
          build: true
markdown_extensions:
  - attr_list
extra_css:
  - assets/extra.css
extra_javascript:
  - assets/extra.js
